version: '3.8'
services:
  db:
    image: postgres:15.2
    restart: 'unless-stopped'
    container_name: weather_db
    environment:
      POSTGRES_DB: 'weather'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - 5432:5432

  redis:
    image: redis:7
    container_name: weather_redis

  db_migration:
    build:
      context: .
      dockerfile: Dockerfile
    restart: 'on-failure'
    depends_on:
      - db
    env_file: .env
    command: sh -c "python3 -m alembic upgrade head"

  weather:
    build:
      context: .
    container_name: weather_app
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
      - db_migration
