version: '3.7'
services:
  db:
    image: postgres:16
    container_name: weather_db
    env_file:
      - .env
    ports:
      - 5432:5432
  
  redis:
    image: redis:7
    container_name: weather_redis

  weather:
    build:
      context: .
    container_name: weather_app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: ["bash/weather/docker/app.sh"]
    ports:
      - 7777:9000