"""UPDATE COLUMNS

Revision ID: 00e029ad12a5
Revises: 39f8629a0a87
Create Date: 2024-05-25 01:24:54.852766

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision = '00e029ad12a5'
down_revision = '39f8629a0a87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    gender_enum = ENUM('Мужчина', 'Женщина', name='genderenum')
    gender_enum.create(op.get_bind())

    op.add_column('clothes', sa.Column('gender', sa.Enum('Мужчина', 'Женщина', name='genderenum'), nullable=False))
    op.add_column('users', sa.Column('gender', sa.Enum('Мужчина', 'Женщина', name='genderenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    op.drop_column('clothes', 'gender')
    # ### end Alembic commands ###
