"""new update

Revision ID: 34337843a528
Revises: 39f8629a0a87
Create Date: 2024-05-25 01:13:50.635945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34337843a528'
down_revision = '39f8629a0a87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clothes', sa.Column('gender', sa.Enum('male', 'female', name='genderenum'), nullable=False))
    op.add_column('users', sa.Column('gender', sa.Enum('male', 'female', name='genderenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    op.drop_column('clothes', 'gender')
    # ### end Alembic commands ###
