"""test mtm

Revision ID: 39f8629a0a87
Revises: a1addf3b7d45
Create Date: 2024-05-24 15:36:36.519466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39f8629a0a87'
down_revision = 'a1addf3b7d45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('clothes_weatherLabels_association',
    sa.Column('clothes_id', sa.Integer(), nullable=True),
    sa.Column('weather_labels_id', sa.Integer(), nullable=True),
    sa.Column('weathers_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clothes_id'], ['clothes.id'], ),
    sa.ForeignKeyConstraint(['weather_labels_id'], ['weather_labels.id'], ),
    sa.ForeignKeyConstraint(['weathers_id'], ['weathers.id'], )
    )
    op.add_column('clothes', sa.Column('temp_min', sa.Integer(), nullable=False))
    op.add_column('clothes', sa.Column('temp_max', sa.Integer(), nullable=False))
    op.drop_constraint('clothes_weather_fkey', 'clothes', type_='foreignkey')
    op.drop_column('clothes', 'weather')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clothes', sa.Column('weather', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('clothes_weather_fkey', 'clothes', 'weathers', ['weather'], ['id'])
    op.drop_column('clothes', 'temp_max')
    op.drop_column('clothes', 'temp_min')
    op.drop_table('clothes_weatherLabels_association')
    op.drop_table('weather_labels')
    # ### end Alembic commands ###
