"""UPDATE COLUMNS

Revision ID: a1632665a139
Revises: 39f8629a0a87
Create Date: 2024-05-25 16:14:12.420690

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1632665a139'
down_revision = '39f8629a0a87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    users_gender_enum = sa.Enum('Мужчина', 'Женщина', name='users_gender_enum')
    users_gender_enum.create(op.get_bind())
    
    op.add_column('clothes', sa.Column('gender', postgresql.ENUM('Мужчина', 'Женщина', name='users_gender_enum'), nullable=False))
    op.add_column('users', sa.Column('gender', postgresql.ENUM('Мужчина', 'Женщина', name='users_gender_enum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    op.drop_column('clothes', 'gender')
    # ### end Alembic commands ###
