"""init2

Revision ID: b16ea815f7b1
Revises: 6bab9622c619
Create Date: 2024-05-17 19:10:27.917045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b16ea815f7b1'
down_revision = '6bab9622c619'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
